### ISSUE TITLE
HGSS Golden Edition Compatability?

### ISSUE THREAD

**Issue by y0miel** [TheGag96/individual-color-variation#11]
Is ICV currently compatible with the HGSS Golden Edition patches? If it is, in what order should I patch my rom? If not, is it in the plans/feasible to make it so?

**Comment by TheGag96** [comment]
I apologize for the delay responding to this. Given that the hack is based on a European ROM, it would be a bit involved to apply this mod to it because various locations in the code may have shifted around. Unfortunately, I just don't think I have the time to support another version like that... Sorry!!
