### ISSUE TITLE
Error with Platinum Patch

### ISSUE THREAD

**Issue by Ansh-ar** [TheGag96/individual-color-variation#8]
While the Heartgold patches worked perfectly I seem to have stumbled into a problem when trying to patch a pokémon platinum clean ROM: using [this patcher](https://kotcrab.github.io/xdelta-wasm/) it returns a checksum error: "Error occurred while patching
Details: target window checksum mismatch (code -17712)".

I tried with past patches and asked some friends to try as well and we seem to all stumble in this same error.

**Comment by TheGag96** [comment]
Which patch file did you try exactly? And could you post the MD5 hash of the Platinum ROM you have?

**Comment by Ansh-ar** [comment]
I tried with v.1.3.Platinum.3541, v.1.1 and v.1.0 and they all returned the same error.
Here's the MD5 Hash: D66AD7A2A0068B5D46E0781CA4953AE9

**Comment by TheGag96** [comment]
Argh, sorry to be late getting back to you on this!!

So that MD5 happens to be the same as my personal Platinum rip, but not the same as the one I used to make most of these patches, which was the 3541 Xenophobia rip with the hash `f8905424f7d8aea299c51ec7580b33d8`. If you can track down that copy, that will work. At the same time, would you want to try out the Following + Renegade Platinum patch along with my mod? You'd have a compatible ROM for that too then.

**Comment by Ansh-ar** [comment]
No worries! I managed to find a 3541 Xenophobia rip and now it patched and works perfectly, thank you very much! I'll probably try them out as well, just to get a really original Platinum experience ahah!

**Comment by TheGag96** [comment]
Glad to hear it. Have fun!!
